spring:
  application:
    name: cms-service

  config:
    import: "optional:zookeeper:"

  datasource:
    url: jdbc:postgresql://localhost:5432/cms_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis
      redis:
        time-to-live: 600000

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always


  cloud:
    zookeeper:
      connect-string: localhost:2181
      config:
        root: /config

  zipkin:
    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8081